name: 'Deploy VNet Bicep with child resources'

on:
  workflow_dispatch:

jobs:
  add-address-space:
    name: Deploy VNet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login with deployment credentials
        id: az-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Bicep
        id: bicep
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            $vnetName = "vnetWithDefaultSubnetIfNotExists"
            $rgName = "rgVnetWithDefaultSubnetIfNotExists"

            try {
              Get-AzVirtualNetwork -Name $vnetName -ResourceGroupName $rgName
              $vnetExists = $true
            }
            catch {
              $vnetExists = $false
            }
            
            $parameters = @{
              virtualNetworkName = $vnetName
              addressPrefixes = @(
                "10.0.0.0/24"
              )
              virtualNetworkExists = $vnetExists
            }

            $deployment = New-AzResourceGroupDeployment `
              -ResourceGroupName $rgName `
              -TemplateFile 'resources/vnet-default-subnet-if-not-exists/main.bicep' `
              -TemplateParameterObject $parameters